// <auto-generated />
namespace obiektowe.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class fix_user : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fix_user));
        
        string IMigrationMetadata.Id
        {
            get { return "201905271859140_fix_user"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
